PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX tw: <http://tw.rpi.edu/schema/>
PREFIX twi: <http://tw.rpi.edu/instances/>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX tool: <http://toolmatch.esipfed.org/schema#>

SELECT ?tool ?label ?description ?page ?version ?image
WHERE
{
    ?tool a <http://toolmatch.esipfed.org/schema#Tool>.
	?tool rdfs:label ?label .
	?tool dc:description ?description .
    ?tool doap:homepage ?page .
    ?tool doap:release ?version .
	OPTIONAL { ?tool foaf:depiction ?image . }
} ORDER BY ?label
